create table if not exists public.gymflow_ai_logs (
  id bigint generated by default as identity primary key,
  gym_id text not null,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  language text not null default 'hinglish' check (language in ('english','hindi','hinglish')),
  question text not null,
  intent text not null default 'knowledge',
  action_type text,
  success boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists gymflow_ai_logs_gym_created_idx on public.gymflow_ai_logs(gym_id, created_at desc);
create index if not exists gymflow_ai_logs_owner_created_idx on public.gymflow_ai_logs(owner_user_id, created_at desc);

alter table public.gymflow_ai_logs enable row level security;
grant select on public.gymflow_ai_logs to authenticated;

drop policy if exists owners_read_own_ai_logs on public.gymflow_ai_logs;
create policy owners_read_own_ai_logs on public.gymflow_ai_logs
for select to authenticated
using ((select auth.uid()) = owner_user_id);
